plaid/plaid-go

plaid/plaid.go
On Google Cloud http.DefaultClient is not available, so we need to pass an alternative implementation when creating new Plaid client.
I know NewClientEx is not the best name. Maybe you can come up with a better one or solve this issue in a different way altogether.
=> On Google Cloud http.DefaultClient is not available

plaid/institutions.go, plaid/institutions_test.go
Addresses https://github.com/plaid/plaid-go/issues/33.  Old `/institutions` endpoints are replaced by new ones:
- `/institutions/all`
- `/institutions/all/:id`
- `/institutions/all/search`
=> Update institutions endpoints

main.go
Previous, `GetInstitution` used to be a package function. That has
changed since https://github.com/plaid/plaid-go/commit/a61bc9dd11501e3d190f25f39c6a3cbe4eb61a36).
This PR updates main.go accordingly.
=> Fix: `GetInstitutions` no longer package function

Gopkg.lock, Gopkg.toml
Bumps `golang.org/x/lint`, `golang.org/x/tools`. I ran into a few problems with `make setup` that this fixes.
=> Bump golang.org/x/{lint,tools}

plaid/investment_transactions_test.go, plaid/transactions_test.go
Sandbox items will not always return transactions for the dates that we've previously written into the tests. This change makes the tests less brittle.
=> Use transaction ranges in tests that have transactions

plaid/processor.go, plaid/processor_test.go
* Adds the function `CreateOcrolusToken` and related test.
* Refactors the shared logic in the `CreateApexToken `, `CreateDwollaToken`, and `CreateOcrolusToken` functions into the `CreateProcessorToken` function. I've left the three processor-specific functions exposed for ease of integration. I also left the Stripe structs and function as-is since Stripe uses bank account tokens instead of processor tokens.
Do we want to export the `CreateProcessorToken` function? Or should we make it unexported?
=> Add support for Ocrolus processor tokens

plaid/institutions_test.go
The institutions data changes frequently, so any tests that are written directly against institution names are liable to break. If there is not enough traffic to accurately calculate institution status, as is the case in the sandbox environment, the API returns null rather than potentially inaccurate data.
=> Fix TestGetInstitutions and TestGetInstitutionsByID

plaid/item.go
Adds the long missing `status` field to item/get including support for transactions and investments products
Fixes: #72 and #73
=> add support for the `status` object in /item/get

plaid/item.go, plaid/item_test.go
Follow-up to https://github.com/plaid/plaid-go/pull/92#issuecomment-576671534. The `ItemStatus` field should be scoped to `GetItemResponse.Status`, not `GetItemResponse.Item.Status`. The diff is easier to follow if you [ignore whitespace](https://github.com/plaid/plaid-go/pull/93/files?w=1).
=> Fix status object in /item/get response

main.go, plaid/webhooks.go, plaid/webhooks_test.go
Add support for the `/webhook_verification_key/get` endpoint in `plaid-go
=> Add /webhook_verification_key/get endpoint to plaid-go

plaid/api_test.go, plaid/institutions.go, plaid/institutions_test.go
Adds support for a new `oauth` request option for `/institutions/get` and `/institutions/search`, and adds a new `oauth` field to the institution schema returned by `/institutions/get`, `/institutions/get_by_id`, and `/institutions/search`.
=> Add OAuth support to /institutions endpoints

plaid/sandbox.go
Picking up where https://github.com/plaid/plaid-go/pull/77 left off
```
package main
import (
"fmt"
"net/http"
"github.com/plaid/plaid-go/plaid"
)
func handleError(err error) {
if err != nil {
panic(err)
}
}
func main() {
// Creates a new Plaid Client
clientOptions := plaid.ClientOptions{
"...",
"...",
"...",
plaid.Sandbox,
&http.Client{},
}
client, err := plaid.NewClient(clientOptions)
handleError(err)
resp, err := client.SetSandboxItemVerificationStatus("...", "qge3n39V4didmAbA6R7JiMXaj4zm5GFdPjgE7", "verification_expired")
handleError(err)
fmt.Println(resp)
}
```
=> Set verification status sandbox endpoint

plaid/accounts_test.go
Tests appear to be failing because of this assumption.
=> Don't assume a particular number of sandbox accounts

plaid/transactions.go
Adds the missing `authorized_date` and `payment_channel` fields to the `Transaction` struct.
Related Issue: #102 
References:
- [The **Changelog - January 2020** Blog Post](https://blog.plaid.com/changelog-january-2020/)
- [The **Transaction Schema** Documentation](plaid.com/docs/#transaction-schema)
=> Add authorized_date and payment_channel to Transaction struct

plaid/link_token_test.go
The phone number we were using "1234567890" is not a valid phone number. This updates the test to use a valid phone number instead.
=> Fix link token unit test

main.go, plaid/institutions.go, plaid/institutions_test.go
Country codes are now required for the /institutions/ API endpoints. This updates the client library to properly take a country_codes field
=> Add country codes to institutions/ endpoints

CHANGELOG.md, README.md, main.go, plaid/institutions.go, plaid/institutions_test.go, plaid/item.go, plaid/item_test.go, plaid/payment.go, plaid/payment_test.go, plaid/plaid.go
1. Removed the legacy token implementations
2. Removed the tests associated with the legacy tokens
3. Updated tests to no longer check for the removed flag in the /item/remove response
4. Updated /payment/get test to no longer check for payment_token or payment_token_expiration_time
=> remove legacy token endpoints

plaid/liabilities.go, plaid/liabilities_test.go
Issue #148 
Mortgage information from the JSON was not present in the `GetLiabilitiesResponse` struct.
resolves #148
=> Issue #148 - added mortgage information to liabilities response

plaid/institutions.go, plaid/institutions_test.go
Here's a PR for issue #132 I opened a few months ago. I see that @skylarmb had started on this with #140, so if you'd rather finish that up and merge that one, that works for me.
- Adds `RoutingNumbers` field to `Institutions` and `GetInstitutionsOptions` structs
- Edits `TestGetInstitutions` to use a table format to make it easier to have multiple subtests
- Adds a subtest in `TestGetInstitutions` to test specifying routing numbers in the request
- Resolves #132
=> Add Routing Numbers to Institutions

plaid/item.go, plaid/item_test.go, plaid/payment.go, plaid/payment_test.go
Add back support for the legacy token create endpoints but mark them as deprecated since we advise new client library users from using them. They will be supported in this version but will eventually be eventually be removed for real in some future version.
- /item/public_token/create
- /item/add_token/create
- /payment_initiation/payment/token/create
=> add back legacy token endpoints but mark them as deprecated

plaid/api_test.go, plaid/institutions.go, plaid/institutions_test.go
Adds payment_initiation metadata support:
- Returns some more information in the institutions endpoints response.
- Adds in an options parameter to filter institutions by payment id.
=> Adds payment_initiation metadata support

plaid/accounts.go, plaid/accounts_test.go, plaid/api_test.go
- Adds last_updated_datetime field to /accounts/balance/get result.
- Adds min_last_updated_datetime option to /accounts/balance/get request.
=> Add last_updated_datetime handling for /accounts/balance/get
