plaid/connect.go
Fixes https://github.com/plaid/plaid-go/issues/21.
=> ConnectStep: fix API endpoint

README.md
Just noticed a small URL glitch while reading through the examples.
=> Update MFA link

plaid/auth.go, plaid/balance.go, plaid/connect.go, plaid/exchange-token.go, plaid/plaid.go, plaid/upgrade.go
This PR addresses: https://github.com/plaid/plaid-go/issues/15. This brings more clarity and the order of the fields does not necessarily have to maintained anymore. 
/cc @soroushjp
=> Use keyed struct fields for clarity

plaid/processor.go, plaid/processor_test.go
- https://plaid.com/docs/link/stripe/#step-4-write-server-side-handler
- https://plaid.com/docs/link/dwolla/#step-4-write-server-side-handler
=> add /processor endpoints

plaid/accounts_test.go, plaid/institutions_test.go, plaid/processor_test.go
these tests don't appear to have been passing. patching them so they do.
=> fix CI tests to pass

plaid/institutions.go, plaid/institutions_test.go
change requires a version update. adds options to all institution methods.
=> add options to all Institution requests

plaid/accounts.go, plaid/auth.go
Fixes https://github.com/plaid/plaid-go/issues/63
=> Fix auth EFT response schema

PUBLISH.md
Addresses https://github.com/plaid/plaid-go/issues/13
=> Add PUBLISH.md

plaid/liabilities.go, plaid/liabilities_test.go
Adds a wrapper for `/liabilities/get`.
=> Add support for liabilities product

plaid/holdings.go
fix for: https://github.com/plaid/plaid-go/issues/78
=> holdings: add options to retrieve holdings request

plaid/holdings_test.go
add a test for the changes in: #80
=> holdings: add test for account_ids option

plaid/institutions.go
Adding a new optional field, `options.account_filter`, to `/institutions/search`.
=> Adding field options.account_filter

plaid/item.go
This field is documented in the [item schema](https://plaid.com/docs/#item-schema) docs.
The CI failures are unrelated ([CLIB-192811](https://jira.plaid.com/browse/CLIB-192811)).
=> Add consent expiration time to Item struct

main.go, plaid/payment.go, plaid/payment_test.go
Implements UK payment initiation client library
=> Implements UK payment initiation client library

plaid/investment_transactions.go, plaid/investment_transactions_test.go
=> investment_transactions: add Subtype

plaid/transactions.go, plaid/transactions_test.go
Adds function to call /transactions/refresh
=> Add transactions refresh route + test

plaid/institutions_test.go, plaid/transactions.go
Also fixes a test that broke due to an institution status issue.
=> Add transaction_code to Transaction struct

README.md
Add a 'developing' section with test notes. Contribution section was missing.
=> Add dev + testing details to README

plaid/item.go, plaid/item_test.go
This depends on #110, will rebase on top of `master` once that gets merged.
(Note test won't pass until the new field is introduced on our end)
=> Add client_user_id field

plaid/auth.go, plaid/auth_test.go, plaid/item_test.go
https://github.com/plaid/plaid-go/issues/118
=> add GetAuthResponse.Item

README.md, main.go, plaid/api_test.go, plaid/institutions.go, plaid/plaid.go, plaid/sandbox.go
This lib should no longer require the public_key.
=> remove the public key

plaid/link_token_test.go
Pass back language and country code in /link/token/create test
=> add more required fields

main.go, plaid/payment.go, plaid/payment_test.go
Supports creating Standing Orders through this client library
=> Add Standing Order support to Payment Initiation

plaid/institutions.go
=> Add investments_updates & health_incidents to InstitutionStatus

CHANGELOG.md
=> 7.2.0 changelog

main.go, plaid/payment.go, plaid/payment_test.go
- Add new create payment function that accepts payment options.
=> Adds support for new payment initiation options
